export enum ValidationErrorsEnum {
  errorPassword1= 'Password must contain at least 1 uppercase, 1 lowercase, 1 symbol, and 1 number',
  errorPassword2= '\'password\' length must be at least 8 characters long',
  errorDisplayNameEmpty= '\'DisplayName\' is not allowed to be empty',
  errorEmailEmpty = '\'email\' is not allowed to be empty',
  errorPasswordEmpty= '\'password\' is not allowed to be empty',
  errorDisplayNameNull = '\'DisplayName\' must be a text',
  errorEmailNull = '\'email\' must be a text',
  errorPasswordNull= '\'password\' must be a text',
  errorEmailInvalid = '\'email\' must be a valid email',
  errorUserExist = 'already exists',
  userCreated = 'User is created',
  userSizeMin = '\'DisplayName\' must be at least 3 characters long',
  userSizeMax= '\'DisplayName\' must not be longer than 30 characters long',
  customFieldNotAllowed = 'Custom Field is not allowed',
  emailFailure = 'Email Failure',
  tokenError = 'This account is either active, or the token is invalid',
  accountActivated = 'Account is activated',
  validationFailure = 'Validation Failure',
  userNotFound = 'User not found',
  authFailure = 'Incorrect credential',
  inactiveAccount = 'Account is inactive',
  unauthorizedUserUpdate = 'You are not authorized to update user',
  unauthorizedUserDelete = 'You are not authorized to delete user',
  confirmPasswordNotMatch = 'Passwords do not match',
  confirmPasswordRequired = 'Confirm password is required'
}
